apiVersion: v1
kind: Pod
metadata:
  name: python-app
  namespace: airflowop-system
  labels:
    app: python
spec:
  containers:
  - name: python-app
    image: "ubuntu:16.04"
    resources:
        limits:
          cpu: "100m"
          memory: "500Mi"
        requests:
          cpu: "100m"
          memory: "500Mi"
  nodeName: gl1-cp-tr-node1.gl-hpe.local
  nodeSelector:
    kubernetes.io/hostname: gl1-cp-tr-node1.gl-hpe.local
